"""
Pydantic v2 models for dynamic agent planning and execution.

Provides typed boundaries for plan/guard/stop-condition models and unified Settings
configuration that replaces LLMConfig with agent-specific extensions.
"""

import os
import warnings
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Dict, Any, List, Optional, Union
import json

from pydantic import BaseModel, Field
from pydantic_settings import BaseSettings


class Intent(str, Enum):
    """User intent classification for query routing and tool selection."""
    PRESENCE_ABSENCE = "presence_absence"
    QUANTIFICATION = "quantification" 
    SPATIAL_NEIGHBORHOOD = "spatial_neighborhood"
    NOVELTY_SCAN = "novelty_scan"
    GENERIC_QNA = "generic_qna"


class Guard(BaseModel):
    """
    Opaque guard descriptor for tool eligibility gating.
    
    Guards are evaluated by policy_engine to determine if a tool
    can be invoked given current context and evidence state.
    """
    name: str = Field(description="Guard predicate name (e.g., 'requires_anchor')")
    args: Dict[str, Any] = Field(default_factory=dict, description="Guard parameters")


class StopCondition(BaseModel):
    """
    Stop condition descriptor for early exit from agent loops.
    
    Consumed by policy_engine to determine if execution should
    terminate based on evidence state and intent satisfaction.
    """
    name: str = Field(description="Stop condition name (e.g., 'presence_absence_conclusive')")
    args: Dict[str, Any] = Field(default_factory=dict, description="Condition parameters")


class PlanStep(BaseModel):
    """
    Individual step in an agent execution plan.
    
    Represents a single tool invocation with dependencies,
    cost information, and control flow conditions.
    """
    tool: str = Field(description="Tool name to execute")
    args: Dict[str, Any] = Field(default_factory=dict, description="Tool-specific arguments")
    requires: List[str] = Field(default_factory=list, description="Named capabilities or prior step IDs required")
    cost: str = Field(description="Cost tier: cheap, moderate, expensive")
    guards: List[Guard] = Field(default_factory=list, description="Eligibility guards that must pass")
    stop_on: List[StopCondition] = Field(default_factory=list, description="Conditions that terminate execution")
    id: str = Field(description="Stable step identifier for dependency tracking")


class Plan(BaseModel):
    """
    Complete agent execution plan with intent and structured steps.
    
    Generated by planner and consumed by executor for dynamic
    execution with early exit capabilities.
    """
    intent: Intent = Field(description="Classified user intent")
    steps: List[PlanStep] = Field(description="Ordered execution steps")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Planning context and debug info")


class ToolInput(BaseModel):
    """Standardized tool input contract."""
    tool: str = Field(description="Tool name")
    args: Dict[str, Any] = Field(description="Tool arguments")


class ToolOutput(BaseModel):
    """Standardized tool output contract with metrics."""
    tool: str = Field(description="Tool name that produced output")
    success: bool = Field(description="Whether tool execution succeeded")
    summary: str = Field(description="Human-readable result summary")
    artifacts: Dict[str, Any] = Field(default_factory=dict, description="Structured tool results")
    metrics: Dict[str, Any] = Field(default_factory=dict, description="Performance and evidence metrics")


class EvidenceLedger(BaseModel):
    """
    Complete audit trail of agent execution with evidence tracking.
    
    Records all tool invocations, intermediate results, and final
    verdict for query analysis and debugging.
    """
    query: str = Field(description="Original user query")
    plan_snapshot: Plan = Field(description="Initial execution plan")
    calls: List[ToolOutput] = Field(default_factory=list, description="Tool execution history")
    final_verdict: Optional[Dict[str, Any]] = Field(default=None, description="Conclusiveness assessment")
    
    def safe_summary(self) -> Dict[str, Any]:
        """Return minimal JSON-serializable dict with no secrets."""
        return {
            "query": self.query[:100] + "..." if len(self.query) > 100 else self.query,
            "intent": self.plan_snapshot.intent,
            "steps_planned": len(self.plan_snapshot.steps),
            "tools_executed": len(self.calls),
            "successful_calls": sum(1 for call in self.calls if call.success),
            "final_state": self.final_verdict.get("state") if self.final_verdict else "incomplete",
            "timestamp": datetime.now().isoformat()
        }


class Settings(BaseSettings):
    """
    Unified configuration for agent planning and execution.
    
    Absorbs LLMConfig functionality and adds agent-specific settings
    for dynamic planning, evidence tracking, and cost management.
    """
    
    # Database connections (inherited from LLMConfig)
    neo4j_uri: str = Field(default="bolt://localhost:7687", description="Neo4j connection URI")
    neo4j_user: str = Field(default="neo4j", description="Neo4j username") 
    neo4j_password: str = Field(default="your_new_password", description="Neo4j password")
    lancedb_path: str = Field(default="data/stage08_esm2/lancedb", description="LanceDB database path")
    
    # LLM provider settings (inherited from LLMConfig)
    llm_provider: str = Field(default="openai", description="LLM provider")
    llm_model: str = Field(default="gpt-5-2025-08-07", description="Default LLM model")
    openai_api_key: Optional[str] = Field(default=None, description="OpenAI API key")
    anthropic_api_key: Optional[str] = Field(default=None, description="Anthropic API key")
    
    # Model allocation (inherited from LLMConfig)  
    cost_effective_model: str = Field(default="gpt-4.1-mini", description="Cost-effective model")
    premium_model: str = Field(default="gpt-5-2025-08-07", description="Premium model")
    model_mode: str = Field(default="cost_effective", description="Current model mode")
    
    # LLM model selection for agent components
    llm_model_planner: str = Field(default="gpt-5-2025-08-07", description="Model for planning tasks")
    llm_model_responder: str = Field(default="gpt-4.1-mini", description="Model for response generation")
    
    # Embedding settings (inherited from LLMConfig)
    embedding_model: str = Field(default="text-embedding-3-small", description="Embedding model")
    embedding_dim: int = Field(default=320, description="ESM2 embedding dimension")
    
    # RAG settings (inherited from LLMConfig)
    max_context_length: int = Field(default=8000, description="Maximum context length")
    similarity_threshold: float = Field(default=0.7, description="Similarity threshold for protein search")
    max_results_per_query: int = Field(default=10, description="Maximum results per query")
    
    # Performance settings (inherited from LLMConfig)
    timeout_seconds: int = Field(default=30, description="Query timeout")
    cache_enabled: bool = Field(default=True, description="Enable query result caching")
    
    # Agent-specific budget and performance controls
    max_budget_tokens: int = Field(default=100000, description="Maximum tokens per query execution")
    max_wallclock_seconds: int = Field(default=300, description="Maximum execution time in seconds")
    expensive_tool_cost_hint: int = Field(default=1000, description="Relative cost scale for expensive tools")
    
    # Evidence and vector search thresholds
    vector_hit_threshold: float = Field(default=0.7, description="Minimum similarity for vector evidence")
    evidence_ledger_dir: str = Field(default="data/session_notes/{session_id}/evidence", description="Evidence JSON storage directory")
    
    class Config:
        env_prefix = "GENOMIC_RAG_"
        env_file = ".env"
        case_sensitive = False
    
    @classmethod
    def from_llm_config(cls, llm_config, session_id: Optional[str] = None, **overrides) -> 'Settings':
        """
        Bridge existing LLMConfig callers to unified Settings.
        
        Args:
            llm_config: Existing LLMConfig instance
            session_id: Session ID for evidence ledger path templating
            **overrides: Additional settings to override
            
        Returns:
            Settings instance with LLMConfig values + agent extensions
        """
        # Extract database config
        db_config = getattr(llm_config, 'database', None)
        
        # Map LLMConfig fields to Settings
        settings_data = {
            "neo4j_uri": db_config.neo4j_uri if db_config else "bolt://localhost:7687",
            "neo4j_user": db_config.neo4j_user if db_config else "neo4j", 
            "neo4j_password": db_config.neo4j_password if db_config else "your_new_password",
            "lancedb_path": db_config.lancedb_path if db_config else "data/stage08_esm2/lancedb",
            
            "llm_provider": getattr(llm_config, 'llm_provider', "openai"),
            "llm_model": getattr(llm_config, 'llm_model', "gpt-5-2025-08-07"),
            "openai_api_key": getattr(llm_config, 'openai_api_key', None),
            "anthropic_api_key": getattr(llm_config, 'anthropic_api_key', None),
            
            "cost_effective_model": getattr(llm_config, 'cost_effective_model', "gpt-4.1-mini"),
            "premium_model": getattr(llm_config, 'premium_model', "gpt-5-2025-08-07"),
            "model_mode": getattr(llm_config, 'model_mode', "cost_effective"),
            
            "embedding_model": getattr(llm_config, 'embedding_model', "text-embedding-3-small"),
            "embedding_dim": getattr(llm_config, 'embedding_dim', 320),
            
            "max_context_length": getattr(llm_config, 'max_context_length', 8000),
            "similarity_threshold": getattr(llm_config, 'similarity_threshold', 0.7),
            "max_results_per_query": getattr(llm_config, 'max_results_per_query', 10),
            
            "timeout_seconds": getattr(llm_config, 'timeout_seconds', 30),
            "cache_enabled": getattr(llm_config, 'cache_enabled', True),
            
            # Agent-specific defaults
            "llm_model_planner": getattr(llm_config, 'premium_model', "gpt-5-2025-08-07"),
            "llm_model_responder": getattr(llm_config, 'cost_effective_model', "gpt-4.1-mini"),
        }
        
        # Template evidence ledger directory with session ID
        if session_id:
            settings_data["evidence_ledger_dir"] = f"data/session_notes/{session_id}/evidence"
        
        # Apply overrides
        settings_data.update(overrides)
        
        return cls(**settings_data)
    
    def get_api_key(self) -> Optional[str]:
        """Get the appropriate API key based on provider (LLMConfig compatibility)."""
        if self.llm_provider == "openai":
            return self.openai_api_key or os.getenv('OPENAI_API_KEY')
        elif self.llm_provider == "anthropic":
            return self.anthropic_api_key or os.getenv('ANTHROPIC_API_KEY')
        return None
    
    def get_evidence_ledger_path(self, session_id: str, query_index: int) -> Path:
        """
        Get timestamped evidence ledger file path.
        
        Args:
            session_id: Session identifier
            query_index: Sequential query number within session
            
        Returns:
            Path to evidence JSON file
        """
        # Template the directory path
        evidence_dir = self.evidence_ledger_dir.format(session_id=session_id)
        evidence_path = Path(evidence_dir)
        evidence_path.mkdir(parents=True, exist_ok=True)
        
        # Generate timestamped filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"query_{query_index:03d}_{timestamp}.json"
        
        return evidence_path / filename
    
    def save_evidence_ledger(self, ledger: EvidenceLedger, session_id: str, query_index: int) -> Path:
        """
        Atomically save evidence ledger to JSON file.
        
        Args:
            ledger: EvidenceLedger to persist
            session_id: Session identifier  
            query_index: Sequential query number
            
        Returns:
            Path where ledger was saved
        """
        output_path = self.get_evidence_ledger_path(session_id, query_index)
        
        # Use safe_summary to avoid exposing secrets
        safe_data = ledger.safe_summary()
        safe_data["full_ledger_available"] = True
        safe_data["query_index"] = query_index
        safe_data["session_id"] = session_id
        
        # Atomic write
        temp_path = output_path.with_suffix('.tmp')
        with open(temp_path, 'w') as f:
            json.dump(safe_data, f, indent=2, ensure_ascii=False)
        
        temp_path.rename(output_path)
        return output_path