name: genome-kg
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  # Core bioinformatics tools are installed via homebrew (quast, prodigal)
  # Python packages for bioinformatics
  - pyhmmer
  - biopython
  # Dependencies for dfast_qc
  - ete3
  - more-itertools
  - peewee
  # Data processing and analysis
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pyarrow
  # Knowledge graph and database
  - rdflib
  - neo4j-python-driver
  # Machine learning and retrieval
  - faiss-cpu
  # CLI and utilities
  - typer
  - pydantic
  - click
  - rich
  - requests
  - pyyaml
  - tqdm
  - loguru
  # Development and testing
  - pytest
  - flake8
  - black
  - isort
  - mypy
  # Jupyter environment
  - jupyter
  - notebook
  - ipykernel
  # Package management
  - pip
  - pip:
    - dsp-ml
    - neo4j
