name: genome-kg
channels:
  - conda-forge
  - bioconda
dependencies:
  # --- Core Specification ---
  - python=3.11
  # Use numpy 2.x for better compatibility with modern ML stack
  - numpy

  # --- Machine Learning & AI ---
  - pytorch
  - transformers
  - scikit-learn
  - h5py
  # Vector database for embeddings (replaces FAISS)
  - lancedb
  - pyarrow

  # --- Data & Databases ---
  - pandas
  - scipy
  - pyarrow
  - rdflib
  - neo4j-python-driver
  - peewee

  # --- Bioinformatics ---
  - pyhmmer
  - biopython
  - ete3

  # --- Plotting & Visualization ---
  - matplotlib
  - seaborn

  # --- CLI & Utilities ---
  - typer
  - pydantic
  - click
  - rich
  - requests
  - pyyaml
  - tqdm
  - loguru
  - more-itertools

  # --- Development, Jupyter & Testing ---
  - jupyter
  - notebook
  - ipykernel
  - pytest
  # Moved from pip to conda for better dependency resolution
  - pytest-cov
  - pytest-xdist
  - pytest-asyncio
  - platformdirs
  - flake8
  - black
  - isort
  - mypy